name: Download Models

on:
  push:
    branches:
      - main

jobs:
  download_models:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Download Models
      run: python model_download.py

    - name: Save Models to Main Repo
      run: |
        git config --global user.email "your-email@gmail.com"
        git config --global user.name "Your Name"
        git add ./model/*
        git commit -m "Update models"
        git push
