name: Run Movie Recommender App

on:
  push:
    branches:
      - main

jobs:
  run_app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Movie Recommender App
      run: python app.py

    - name: Save Models to Main Repo
      run: |
        git config --global user.email "almasibryan7@gmail.com"
        git config --global user.name "Asega-bryan07"
        git add ./model/*
        git commit -m "Update models"
        git push
